name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/checkout@v2
      - name: Build :latest
        run: docker build -t ${GITHUB_REPOSITORY}:latest .

      - name: Push to docker hub :latest
        uses: actions-hub/docker@master
        with:
          args: push ${GITHUB_REPOSITORY}:latest

      - name: Add remote origin
        run: |
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

      - name: Deploy to Heroku
        run: |
          git push heroku HEAD:master -f

