name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/checkout@v2
      - name: Build :latest
        run: docker build -t ${GITHUB_REPOSITORY}:latest .

      - name: Push to docker hub :latest
        uses: actions-hub/docker@master
        with:
          args: push ${GITHUB_REPOSITORY}:latest

      - name: Heroku Docker Container Deploy
        uses: lucassarcanjo/heroku-deploy@2.1.17
        with:
          email: ${{ secrets.HEROKU_MAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_path: Dockerfile

