name: Test Docker

on:
  push:
    branches:
      - '**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Start Container
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Stop Container
        if: always()
        run: docker-compose -f "docker-compose.yml" down
