name: Test Send Mail

on:
  push:
    branches:
      - dev

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Send email
        uses: dawidd6/action-send-mail@v3.6.0
        with:
          server_address: mail.gmx.net
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: frc-visualization stage update
          to: lukas.danckwerth@gmx.de
          from: frc-visualization stage ${{ env.RELEASE_VERSION }}
          secure: true
